# Generated by Django 3.2 on 2022-05-30 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('birthPlace', models.CharField(blank=True, max_length=200, null=True)),
                ('birthDate', models.DateTimeField()),
                ('pin', models.IntegerField(blank=True, default=0, null=True)),
                ('nameChanged', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.IntegerField(blank=True, default=0, null=True)),
                ('phone', models.IntegerField(blank=True, default=0, null=True)),
                ('home_phone', models.IntegerField(blank=True, default=0, null=True)),
                ('estate_sublocation', models.CharField(blank=True, max_length=200, null=True)),
                ('plot_village', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('citizenBy', models.CharField(blank=True, max_length=200, null=True)),
                ('marriage_status', models.CharField(blank=True, max_length=200, null=True)),
                ('partner_name', models.CharField(blank=True, max_length=200, null=True)),
                ('maiden_name', models.CharField(blank=True, max_length=200, null=True)),
                ('marriage_detail', models.CharField(blank=True, max_length=200, null=True)),
                ('reason_travel', models.CharField(blank=True, max_length=200, null=True)),
                ('id_number', models.IntegerField(blank=True, default=0, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('job', models.CharField(blank=True, max_length=200, null=True)),
                ('height', models.IntegerField(blank=True, default=0, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=200, null=True)),
                ('mark', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_id', models.IntegerField(blank=True, default=0, null=True)),
                ('mother_passport', models.IntegerField(blank=True, default=0, null=True)),
                ('mother_birthPlace', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_address', models.IntegerField(blank=True, default=0, null=True)),
                ('mother_phone', models.IntegerField(blank=True, default=0, null=True)),
                ('father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('father_id', models.IntegerField(blank=True, default=0, null=True)),
                ('father_passport', models.IntegerField(blank=True, default=0, null=True)),
                ('father_birthPlace', models.CharField(blank=True, max_length=200, null=True)),
                ('father_address', models.IntegerField(blank=True, default=0, null=True)),
                ('father_phone', models.IntegerField(blank=True, default=0, null=True)),
                ('craetedAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Part2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('division', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('relationship', models.CharField(blank=True, max_length=200, null=True)),
                ('id_number', models.IntegerField(blank=True, default=0, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.IntegerField(blank=True, default=0, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Part3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('job', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('id_number', models.IntegerField(blank=True, default=0, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.IntegerField(blank=True, default=0, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Part4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Part5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMethod', models.CharField(blank=True, max_length=200, null=True)),
                ('isPaid', models.BooleanField(default=False)),
                ('paidAt', models.DateTimeField(blank=True, null=True)),
                ('isDelivered', models.BooleanField(default=False)),
                ('deliveredAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='products',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
